### PR TITLE
NoRedInk/make-lambda-package#7 add python3.6 building capabilities

### PR DESCRIPTION
**Pull request by fredvollmer**
TODO: Add tests

### CODE REVIEW

**Comment by jtanios** [comment]
Hey @michaelglass .. is this going to be merged anytime soon?

**Comment by michaelglass** [comment]
We'll be happy to ferry forward when the PR is ready but the PR isn't ready for merge yet. E.g. tests are failing.

**Comment by fredvollmer** [comment]
As soon as I get some free time I can try to make this merge-ready

**Comment by ento** [comment]
FYI, #10 added the `--python` flag as `--runtime` and has been released as [v1.1.0](https://github.com/NoRedInk/make-lambda-package/releases/tag/v1.1.0).

**Pull request closed without merging**
